version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal # Use host.docker.internal for host machine DB access
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MORALIS_API_KEY=${MORALIS_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
